---
title: "plume_model"
output: html_document
---
..
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(raster)
library(tidyverse)
library(here)
library(terra)

rasterOptions(maxmemory = 1e10, progress = "text", timer = TRUE, memfrac = .7)
```

# Ideally, by the end of this, we'd have a working plume model.

points need to be JUST INSIDE ocean raster

### Data Preparation:

Load in ocean: 
```{r}
ocean <- raster(here("new_data", "GIS_output", "EEZ_reclass.tif"))
```

Nitrogen:
```{r}
# Points we want to plume:
pointsN <- read_sf(here("new_data", "GIS_output", "outfalls", "out2"), layer = "outfall_snapN2") %>% 
  dplyr::select(c(2, 27:30))

colnames(pointsN) <- c("registry_id", "avg_dly_flw_mgd", "total_lb_yr", "avg_conc_mg_l", "max_c_mg_l", "geometry")

# Names are from this:
# conc_N <- read_csv(here("new_data", "outfall_n.csv"))

## Daily flow is in Million Gallons/Day MGD
## total load is in lbs/yr

# Convert to CFS and kg/yr

pointsN_cfs <- pointsN %>% 
  mutate(dly_flw_cfs =  avg_dly_flw_mgd * 1.54722865) %>% 
  mutate(kg_yrN = total_lb_yr * 0.453592)

```

```{r}
# Points we want to plume:
pointsP <- read_sf(here("new_data", "GIS_output", "outfalls"), layer = "out_snapP")%>% 
  dplyr::select(c(2, 27:30))

colnames(pointsP) <- c("registry_id", "avg_dly_flw_mgd", "total_lb_yr", "avg_conc_mg_l", "max_c_mg_l", "geometry")

# Names are from this:
# conc_N <- read_csv(here("new_data", "outfall_n.csv"))

## Daily flow is in Million Gallons/Day MGD
## total load is in lbs/yr

#Convert to CFS and kg/yr

pointsP_cfs <- pointsP %>% 
  mutate(dly_flw_cfs =  avg_dly_flw_mgd * 1.54722865) %>% 
  mutate(kg_yrN = total_lb_yr * 0.453592)

```


```{r}
# Modify plume function:
plume_fx <- function(points, raster, c = 0.5, b = 0.65, path){
  
  # points = test_points
  # raster = ocean
  # c = 0.5
  # b = 0.65
  
    # Error Checking:
  if(isLonLat(crs(points)) == FALSE) stop("check CRS, function only works for lon/lat. EPSG 4326 works.")
  if(isLonLat(crs(raster)) == FALSE) stop("check CRS, function only works for lon/lat. EPSG 4326 works.")
  
    # So there's only one row:
    for(i in 1:nrow(points)){
    
      test_pt <- points[i,]
      name <- paste("plume_", i, ".tif", sep = "")
      path2 <- paste(path, name, sep = "/")
      
      ### THIS HAPPENS ONCE
      # Get which cell contains that point
      cell <- cellFromXY(raster, st_coordinates(test_pt$geometry))
      # Duplicate the OG raster
      newraster <- raster
      # Set point = 1
      newraster[cell] <- 1
      
      # Calculate plume area: in KM2
      # This is calculated in the plume_regression step
        p_area <- .0145240 * test_pt$dly_flw_cfs + 7.4778210
      
      ### THIS REPEATS
       tot_area <- 0
       n_runs <- 1
      repeat {
        # get cell names for cells that are 1
        newcell <- Which(newraster>=1, cells = TRUE)
        # Find adjacent cells
        adj <- adjacent(newraster, newcell, directions = 4, pairs = FALSE)
        # Turn them into ones
        newraster[adj] <- 1
        # Create a new "newraster" with new ones:
        newraster <- newraster+raster
        tot_area <- sum(as.vector(area(newraster)*newraster), na.rm = TRUE)
        n_runs <- n_runs+1
        # Repeat function until the area is bigger than the plume:
        if(tot_area >= p_area) break
        if(n_runs == 1000) break}
     
    ###
    ### PLUMING
    ###
       
     # Then I actually need to plume these into the ocean.
       
     # Get the effluent as a value
     effluent <- test_pt$kg_yrN
     # Get the proportion of effluent included in each expansion
     prop_eff <- effluent/n_runs
     
     # Create a plume raster:
     p_raster <- raster
     final <- raster
     final[cell] <- prop_eff
      # Set OG point = effluent
     p_raster[cell] <- 1
     # Then, loop through again:
     p_runs <- 1
     repeat{
        # get cell names for cells that are 1
        p_cell <- Which(final>=1, cells = TRUE)
        # Find adjacent cells
        adj <- adjacent(p_raster, p_cell, directions = 4, pairs = FALSE)
        # Turn them into ones
        p_raster[adj] <- 1
        # Set OG cells to NA's
        p_raster[p_cell] <- NA
        # Get cell numbers for new cells
        e_cell <- Which(p_raster>=1, cells = TRUE)
        # Add effluent proportionally over the new cells
        final[e_cell] <- prop_eff/length(e_cell)
        final <- final + raster
        
        # Conditional for loop ending
        p_runs <- p_runs+1
        # Repeat function until the area is bigger than the plume:
        if(p_runs >= n_runs) break
        if(p_runs == 1000) break}
     
     writeRaster(final, path2, format = "GTiff", overwrite = TRUE)
    }
  }
```

```{r}
# Create path for saving files
pathN <- here("plume_outputs", "outfalls", "outfall_n")
pathP <- here("plume_outputs", "outfalls", "outfall_p")

# test <- raster(here("plume_outputs", "outfalls", "outfall_n", "plume_1.tif"))
# test2 <- raster(here("plume_outputs", "outfalls", "outfall_n", "plume_2.tif"))
# test3 <- raster(here("plume_outputs", "outfalls", "outfall_n", "plume_3.tif"))
# test4 <- raster(here("plume_outputs", "outfalls", "outfall_n", "plume_4.tif"))
# 
# plot(test4)
# 
# points_p_area <- pointsP_cfs %>% 
#    mutate(plumeareaKM = .0145240 * dly_flw_cfs +7.478210)


# Run the plume function
plume_fx(pointsN_cfs, ocean, path = pathN)
plume_fx(pointsP_cfs, ocean, path = pathP)
```


```{r}
### Summing the rasters:
library(terra)

N_files <- list.files(here("plume_outputs", "outfalls", "outfall_n"), full.names = TRUE)
P_files <- list.files(here("plume_outputs", "outfalls", "outfall_p"), full.names = TRUE)

sum_fx <- function(input_files, output){
  # Add first two rasters
  first <- rast(input_files[1])
  second <- rast(input_files[2])
  result <- first+second
  # Add the remaining
  for(i in 3:length(input_files)){
    temp <- rast(input_files[i])
    result <- result + temp
  }
  writeRaster(result, output)
}

sum_fx(N_files, output = here("plume_outputs", "outfalls", "outfall_n.tif"))
sum_fx(P_files, output = here("plume_outputs", "outfalls", "outfall_p.tif"))

outfallP <- raster(here("plume_outputs", "outfalls", "outfall_p.tif"))

plot(outfallP)
```

```{r}
pacific_filesP <- list.files(here("plume_outputs", "pacific_tp"), full.names = TRUE)
sum_fx(pacific_filesP, output = here("plume_outputs", "pac_tp.tif"))
```

```{r}
midwest_filesN <- list.files(here("plume_outputs", "midwest_tn"), full.names = TRUE)
sum_fx(midwest_filesN, output = here("plume_outputs", "midwest_tn.tif"))
```

```{r}
midwest_filesP <- list.files(here("plume_outputs", "midwest_tp"), full.names = TRUE)
sum_fx(midwest_filesP, output = here("plume_outputs", "midwest_tp.tif"))
```

```{r}
northeast_filesN <- list.files(here("plume_outputs", "northeast_tn"), full.names = TRUE)
sum_fx(northeast_filesN, output = here("plume_outputs", "northeast_tn.tif"))
```

```{r}
northeast_filesP <- list.files(here("plume_outputs", "northeast_tp"), full.names = TRUE)
sum_fx(northeast_filesP, output = here("plume_outputs", "northeast_tp.tif"))
```

```{r}
southeast_filesN <- list.files(here("plume_outputs", "southeast_tn"), full.names = TRUE)
sum_fx(southeast_filesN, output = here("plume_outputs", "southeast_tn.tif"))
```

```{r}
southeast_filesP <- list.files(here("plume_outputs", "southeast_tp"), full.names = TRUE)
sum_fx(southeast_filesP, output = here("plume_outputs", "southeast_tp.tif"))
```

```{r}
southwest_filesN <- list.files(here("plume_outputs", "southwest_tn"), full.names = TRUE)
sum_fx(southwest_filesN, output = here("plume_outputs", "southwest_tn.tif"))
```

```{r}
southwest_filesP <- list.files(here("plume_outputs", "southwest_tp"), full.names = TRUE)
sum_fx(southwest_filesP, output = here("plume_outputs", "soutwest_tp.tif"))
```

Sum all the rasters:

```{r}
files_N <- list.files(here("plume_outputs"), pattern = "*tn.tif", full.names = T)

sum_fx(files_N, output = here("plume_outputs", "us_tn_river.tif"))

files_p <- list.files(here("plume_outputs"), pattern = "*tp.tif", full.names = T)
sum_fx(files_p, output = here("plume_outputs", "us_tp_river.tif"))
```

