---
title: "plume_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(raster)
library(tidyverse)
library(here)

rasterOptions(maxmemory = 1e10)
```

# Ideally, by the end of this, we'd have a working plume model.

points need to be JUST INSIDE ocean raster

### Data Preparation:
```{r}
# Points we want to plume:
points <- read_sf(here("new_data", "plume_test"), layer = "points")


### What about a new ocean raster:
### This is in Albers Equal Area Conic, which is in m

z <- raster(res=0.1, crs= 4326)

extent(z)

df <- data.frame(
  lon = c(-180, -180, 0, 0, -180),
  lat = c(90, -90, -90, 90, 90))

polygon <- df %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326) %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("POLYGON")

r <- rasterize(polygon, z, field = 0)

plot(r)
plot(points, add = TRUE)


# Test point for the max drainage area point from SPARROW then add false geometry point
test_pt <- read_csv(here("new_data", "plume_test", "testpt_realval.csv")) %>% 
  cbind(points) %>% 
  st_as_sf() %>% 
  select("CumAreaKM2", "al_tn", "geometry")


```


```{r}
path <- here("scratch", "test_plume")

plume_fx <- function(points, raster, c = 0.5, b = 0.65, path){

    # So there's only one row:
    for(i in 1:nrow(points)){
    
      test_pt <- points[i,]
      name <- paste("plume_", i, ".tif", sep = "")
      path2 <- paste(path, name, sep = "/")
      
      ### THIS HAPPENS ONCE
      # Get which cell contains that point
      cell <- cellFromXY(raster, st_coordinates(test_pt$geometry))
      # Duplicate the OG raster
      newraster <- raster
      # Set point = 1
      newraster[cell] <- 1
      
      # Calculate plume area: in KM2
        c <- 0.5
        b <- 0.65
        p_area <- c*(test_pt$CumAreaKM2^b) *1000
      
      ### THIS REPEATS
       tot_area <- 0
       n_runs <- 1
      repeat {
        # get cell names for cells that are 1
        newcell <- Which(newraster>=1, cells = TRUE)
        # Find adjacent cells
        adj <- adjacent(newraster, newcell, directions = 4, pairs = FALSE)
        # Turn them into ones
        newraster[adj] <- 1
        # Create a new "newraster" with new ones:
        newraster <- newraster+r
        tot_area <- sum(as.vector(area(newraster)*newraster), na.rm = TRUE)
        n_runs <- n_runs+1
        # Repeat function until the area is bigger than the plume:
        if(tot_area >= p_area) break}
     
    ###
    ### PLUMING
    ###
       
     # Then I actually need to plume these into the ocean.
       
     # Get the effluent as a value
     effluent <- test_pt$al_tn
     # Get the proportion of effluent included in each expansion
     prop_eff <- effluent/n_runs
     
     # Create a plume raster:
     p_raster <- raster
     final <- raster
     final[cell] <- prop_eff
      # Set OG point = effluent
     p_raster[cell] <- 1
     # Then, loop through again:
     p_runs <- 1
     repeat{
        # get cell names for cells that are 1
        p_cell <- Which(final>=1, cells = TRUE)
        # Find adjacent cells
        adj <- adjacent(p_raster, p_cell, directions = 4, pairs = FALSE)
        # Turn them into ones
        p_raster[adj] <- 1
        # Set OG cells to NA's
        p_raster[p_cell] <- NA
        # Get cell numbers for new cells
        e_cell <- Which(p_raster>=1, cells = TRUE)
        # Add effluent proportionally over the new cells
        final[e_cell] <- prop_eff/length(e_cell)
        final <- final + r
        
        # Conditional for loop ending
        p_runs <- p_runs+1
        # Repeat function until the area is bigger than the plume:
        if(p_runs >= n_runs) break}
     
     writeRaster(final, path2, format = "GTiff", overwrite = TRUE)
    }
  }

plume_fx(test_pt, r, path = path)

didit <- raster(here("scratch", "test_plume", "plume_1.tif"))

plot(didit)
```


```{r}
### Troubleshooting



test_pt <- test_pt[1,]

      
      ### THIS HAPPENS ONCE
      # Get which cell contains that point
      cell <- cellFromXY(r, st_coordinates(test_pt$geometry))
      # Duplicate the OG raster
      newraster <- r
      # Set point = 1
      newraster[cell] <- 1
      
      # Calculate plume area: in KM2
        c <- 0.5
        b <- 0.65
        p_area <- c*(test_pt$CumAreaKM2^b) *1000
      
      ### THIS REPEATS
       tot_area <- 0
       n_runs <- 1
      repeat {
        # get cell names for cells that are 1
        newcell <- Which(newraster>=1, cells = TRUE)
        # Find adjacent cells
        adj <- adjacent(newraster, newcell, directions = 4, pairs = FALSE)
        # Turn them into ones
        newraster[adj] <- 1
        # Create a new "newraster" with new ones:
        newraster <- newraster+r
        tot_area <- sum(as.vector(area(newraster)*newraster), na.rm = TRUE)
        n_runs <- n_runs+1
        # Repeat function until the area is bigger than the plume:
        if(tot_area >= p_area) break}
       
       plot(newraster)
       
       
       ### Works until here...
```

```{r}
effluent <- test_pt$al_tn
     # Get the proportion of effluent included in each expansion
     prop_eff <- effluent/n_runs
     
     # Create a plume raster:
     p_raster <- r
     final <- r
     final[cell] <- prop_eff
      # Set OG point = effluent
     p_raster[cell] <- 1
     # Then, loop through again:
     p_runs = 0
     repeat{
        # get cell names for cells that are 1
        p_cell <- Which(final>=1, cells = TRUE)
        # Find adjacent cells
        adj <- adjacent(p_raster, p_cell, directions = 4, pairs = FALSE)
        # Turn them into ones
        p_raster[adj] <- 1
        # Set OG cells to NA's
        p_raster[p_cell] <- NA
        # Get cell numbers for new cells
        e_cell <- Which(p_raster>=1, cells = TRUE)
        # Add effluent proportionally over the new cells
        final[e_cell] <- prop_eff/length(e_cell)
        final <- final + r
        
        # Conditional for loop ending
        p_runs <- p_runs+1
        # Repeat function until the area is bigger than the plume:
        if(p_runs >= n_runs) break}
    })
     
     plot(final)
     plot(p_raster)
```



